// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230120191807_FixData")]
    partial class FixData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Age")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.Property<string>("Weight")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = "7m",
                            Name = "Fireheart",
                            Sex = "Male",
                            Species = "Cat",
                            Weight = "6.8lbs"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = "4m",
                            Name = "Honey Buns",
                            Sex = "Female",
                            Species = "Cat",
                            Weight = "4.6lbs"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = "6y",
                            Name = "Ceecee",
                            Sex = "Female",
                            Species = "Cat",
                            Weight = "14.9lbs"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = "10y 8m",
                            Name = "Clint",
                            Sex = "Male",
                            Species = "Cat",
                            Weight = "15.8lbs"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = "9m",
                            Name = "Lucas",
                            Sex = "Male",
                            Species = "Dog",
                            Weight = "50lbs"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = "2y 2m",
                            Name = "Dexter",
                            Sex = "Male",
                            Species = "Dog",
                            Weight = "66.4lbs"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = "1y 7m",
                            Name = "Forrester",
                            Sex = "Male",
                            Species = "Dog",
                            Weight = "51.5lbs"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = "1y 11m",
                            Name = "Oliver",
                            Sex = "Male",
                            Species = "Dog",
                            Weight = "63lbs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
